name = "goosegrid-micro-trader"
compatibility_date = "2026-05-10"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mtl_micro_trader"
database_id = "41f648ae-25de-47af-bcd9-5d36a80b9164"
